// <auto-generated />
namespace Inventory_Management_iTransition.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class itemsChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemsChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202509091437248_itemsChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
